---
- name: "Run 10_SLES_register.yml"
  import_playbook: 10_SLES_register.yml

- name: "Run 20_SLES_register_SUSE_HA.yml"
  import_playbook: 20_SLES_register_SUSE_HA.yml

- name: 'Basic configuration on all nodes'
  hosts: 'all'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'zypper_ref_accept_keys'
    - role: 'set_hostname'
    - role: 'add_all_nodes_to_etc_hosts'
      vars:
        group_name: 'all'
    - role: 'install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - 'hostname'
          - 'nginx'
    - role: 'minimal_bashrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'create_a_vimrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'install_chrony'
    - role: 'set_ntp_servers_for_chrony'
    - role: 'put_hostname_into_index_html'
      vars:
        path_to_index_html: '/srv/www/htdocs/index.html'
    - role: 'start_and_or_enable_systemd_service'
      vars:
        service_name: 'nginx'
        service_started: 'true'
        service_enabled: 'true'

- name: 'Run playbook playbook-vagrant-keepalived.yml'
  import_playbook: playbook-vagrant-keepalived.yml
  # comment the previous line and uncomment the following line
  # for the scenario with only one virtual IP
  # import_playbook: playbook-vagrant-keepalived-one_virtual_IP.yml
